---
slug: try_programming
filename: try_programming
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2014
uuid: 1993a013-a784-4e54-aa92-a4d31ecd1000
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
